### ISSUE TITLE
consider using lerna

### ISSUE THREAD

**Issue by graingert** [istanbuljs/istanbul-lib-instrument#9] opened 2016-06-27 10:24 UTC
consider using https://github.com/lerna/lerna

except maybe not for "nyc"?

**Comment by gotwarlost** [comment] 2016-06-27 14:44
Personally, I really do not want anything fancy on top of npm. I would rather work on multiple repos and manually keep versions in sync rather than introduce yet another "framework". I'll let others comment and see what their opinions are.

@bcoe - what do you think?

**Comment by bcoe** [comment] 2016-06-27 15:55
@gotwarlost my personal preference is to keep libraries in separate repos, and to use [greenkeeper.io](https://greenkeeper.io/) to keep updates consistent across projects. see [yargs](https://github.com/yargs).

I can understand the mono-repo approach, and there are pluses and minuses to both. Here's what I like about keeping separate repos:

* it helps encourage you to write clean documentation for each repo (I find the packages inside babel, as an example, sometimes have fairly sparse documentation).
* I find it easier to use modules independently, if I can discover their own distinct GitHub repo.

I certainly see the value of `ierna`, and some projects that use monorepos are amazing! so I think it comes down to personal preference in a lot of ways.

**Comment by graingert** [comment] 2016-06-27 16:08
I mainly see the advantage being there's only one place for issue tracking. People will use babel-plugin-istanbul and file issues with it, when the route cause is in istanbul-lib-instrument

**Comment by bcoe** [comment] 2016-06-27 16:24
@graingert one approach I've seen for this (which we're using at npm) are publish issue trackers for the project as a whole:

https://github.com/npm/registry

Perhaps to address this concern, we should create a similar repo for Istanbul?

**Comment by bcoe** [comment] 2016-06-30 16:56
I'm going to leave this open until we get a global issue tracker created to address @graingert's concerns.

**Comment by graingert** [comment] 2016-06-30 16:57
@bcoe you won't be able to auto close issues with PRs then.

**Comment by motiz88** [comment] 2016-10-17 04:47
I'd like to chime in and say that a monorepo is good not just for issue _tracking_ but for issue _fixing_. To debug the issue in #26 coming from `babel-plugin-istanbul` I had to clone two separate repos, `npm link` them together, deal with broken prepublish steps, trace execution across two projects, identify the correct repo to submit a PR to... Which all adds up to a higher barrier to entry for casual or first-time contributors.

**Comment by motiz88** [comment] 2016-10-17 04:54
Also, running tests all at once (for a tightly integrated group of packages performing a particular task together) guards against subtle regressions - and breaking people's builds - in a way that publishing one-by-one and checking with Greenkeeper doesn't. Unless you manually set up CI for each repo to pull the rest of the packages and test against them - by which time you're well on your way to reinventing Lerna with shell scripts :)

**Comment by motiz88** [comment] 2016-10-18 12:05
...and developing https://github.com/istanbuljs/babel-plugin-istanbul/issues/4#issuecomment-254309187 without a monorepo is just crazy. Which is not to say I'm not doing it :face_with_head_bandage: But please, it makes so much more sense to use Lerna for this thing.

**Comment by bcoe** [comment] 2017-02-06 21:22
@motiz88 @graingert, having worked more closely with the folks working on babel (CC: @hzoo), and having a better understanding of lerna, I'm pretty sold on moving some of the Istanbul org into a lerna repo -- I'm thinking we could start by moving pretty much everything prefixed with `istanbul-*`.

Haven't had an uninterrupted block of time to do this yet, but am excited by the idea.

**Comment by graingert** [comment] 2017-02-07 10:16
Make sure you keep the git history!

**Comment by graingert** [comment] 2017-02-08 11:08
@bcoe here's a repo I made that's a merge of all the relevant repos: https://github.com/graingert/istanbul-lerna/

**Comment by graingert** [comment] 2017-02-08 11:10
I've also included babel-plugin-istanbul and nyc, and excluded istanbul.github.io

**Comment by bcoe** [comment] 2017-02-09 06:39
a couple thoughts, questions, and comments:

* I wonder what the best way to maintain git-history would be; one of the advantages I see to moving to lerna is cutting down on the number of repositories in the organization.
  * I might ask some folks who know more about git than myself, and try to get some advice on how they'd approach this.
* I probably won't add nyc into the lerna repo:
  * it started its life as a separate project, and I'd like to maintain a bit of separation.
  * its test suite, and project structure is significantly different.
* I'm slightly on the fence about babel-plugin-istanbul too, mainly because it's a slightly different structure (and more divergent version range).
* I'd like to take advantage of the fact that we're moving to a mono-repo more:
  * have tests managed at the top-level (`npm test` should run tests for the entire suite).
  * correct me if I'm wrong, but does it simplify things if all of the `/packages` get released at the same version #? how does lerna manage multiple packages at multiple version #s?

_edit: having re-read lerna docs, I **think** if we were to drop `nyc` and `babel-plugin-istanbul`  from the lerna repo, we might be close to being able to run in --independent mode_.

**Comment by graingert** [comment] 2017-02-09 09:56
@bcoe 
1. To maintain git history I moved all the code into one directory and used [git-reparent](https://github.com/MarkLodato/git-reparent) to post-hoc mash the history into the correct state.[ See the 9 parent commit?](https://github.com/graingert/istanbul-lerna/commit/b0c53b8de8c01abad6f840fbadf321b72ddb0fa5) It's both technically correct and looks super cool in git guis.
2. I think it makes sense to exclude nyc (for now), and include istanbul.github.io in /docs using the "master branch as github pages" feature. Still I'd like to see nyc included eventually, but I see the reason for excluding it, if only so the repo doesn't collect too much history if it ever wants to split again.
3. babel-plugin-istanbul is fine in lerna imhop, lerna can handle different structures.
4. re lerna
    1. I'm not sure how babel manages their tests pinging @hzoo but I think they have tests in each package, then run each test in turn from their global package.json?
    2. Lerna has two ways of managing versions, [Fixed/locked mode](https://github.com/lerna/lerna#fixedlocked-mode-default) and [Independent mode](https://github.com/lerna/lerna#independent-mode---independent)

**Comment by bcoe** [comment] 2017-02-09 18:42
@graingert let's move forward using [this repo](https://github.com/istanbuljs/istanbuljs):

* let's keep `nyc`/`babel-plugin-istanbull`/`istanbul.github.io` out for the time being (and not add their histories. 
  * I have some ongoing work I'd like to do around babel-plugin-istanbul, before we pull it in.
  * we've already discussed `nyc`.
  * I'm not the biggest fan of a github pages branch, because it feels weird having one repo be two things essentially -- I'd rather just keep this repo separate for the time being.

* I've setup a mono repo for tests at npm, Inc before; and I setup the babel repo itself for test-coverage ... I'm happy to take on this work 👍

**Comment by graingert** [comment] 2017-02-09 18:44
> I'm not the biggest fan of a github pages branch

It would not be a branch, it would just be a /docs directory.

**Comment by bcoe** [comment] 2017-02-09 18:46
@graingert I'd prefer to keep the website separate, since it has a much different build step, and release process than the modules themselves in this org.

**Comment by graingert** [comment] 2017-02-09 18:47
@bcoe ah I thought it would be a plain gh-pages repo.

**Comment by bcoe** [comment] 2017-02-09 18:50
@graingert the README could use some cleanup to reflect the fact, but @MoOx did an amazing job of moving us over to the [phenomic](https://github.com/MoOx/phenomic) framework for the website.

I think it's worth keeping this separate.

**Comment by bcoe** [comment] 2017-02-09 18:53
@graingert I have a pretty busy work day, but will start opening some issues on the mono repo tonight:

* I'm happy to take on the test bit of things.
* I'd like to figure out how we manage the changelog in this type of repo:
  * I love this tool: https://github.com/conventional-changelog/standard-version but I think we'll need to make some changes to make it play nice.

**Comment by graingert** [comment] 2017-02-09 19:10
@bcoe let's move the discussion to that repo. I've got it all setup without nyc/babel-plugin-istanbull/istanbul.github.io

**Comment by bcoe** [comment] 2017-02-09 19:42
@graingert great work, love how you pulled in the git history 👍

**Comment by graingert** [comment] 2017-02-09 19:43
You've got @MarkLodator and https://github.com/MarkLodato/git-reparent to thank for that

**Closed** 2017-02-09 19:42 UTC

**Comment by graingert** [comment] 2017-02-09 19:43
You've got @MarkLodato and https://github.com/MarkLodato/git-reparent to thank for that
